#!/usr/bin/perl -w
use strict;
use File::Copy;

use esmith::DomainsDB;
my $domainsDb = esmith::DomainsDB->open_ro();
my @domains =  $domainsDb->domains();

foreach my $domain (@domains) {
    my $domainName = $domain->key;
    #verify if keys exist
    next if (-f "/etc/opendkim/keys/$domainName.private");
    next if (-f "/etc/opendkim/keys/$domainName.txt");

    system ("/usr/sbin/opendkim-genkey -b 2048 -D /etc/opendkim/keys/ -d $domainName -s $domainName") == '0'||
            die "Opendkim cannot create keys for $domainName: $?";
}

#cp to a world readable place
foreach my $file ( glob "/etc/opendkim/keys/*.txt"){
    copy("$file",'/etc/opendkim/') or die "cannot copy the $file key txt : $?";
}
