#!/usr/bin/perl -w
use strict;
use File::Copy;

use esmith::DomainsDB;
my $domainsDb = esmith::DomainsDB->open_ro();
my @domains =  $domainsDb->domains();

foreach my $domain (@domains) {
    my $domainName = $domain->key;
    #cp to a world readable place
    copy("/etc/opendkim/keys/$domainName.txt",'/etc/opendkim/') 
        or die "cannot copy the key $domainName.txt : $?";
    #verify if keys exist
    next if (-f "/etc/opendkim/keys/$domainName.private");
    next if (-f "/etc/opendkim/keys/$domainName.txt");

    system ("/usr/sbin/opendkim-genkey -b 2048 -D /etc/opendkim/keys/ -d $domainName -s $domainName") == '0'||
            die "Opendkim cannot create keys for $domainName: $?";
}
